### ISSUE TITLE
Complete searchChangeHandler method

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#22]
You have to extract the **_searchTerm_** from the input field and use it for calling **_performSearch_** method.

**Comment by abhishekbhaware** [comment]
can i work on this project

**Comment by niftyy** [comment]
sure, go ahead

**Comment by niftyy** [comment]
updates @abhishekbhaware ?

**Comment by abhishekbhaware** [comment]
Don't copy code to resolve merge conflicts, refer to this :
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
to sync your fork, then apply the changes. Don't use jquery for getting searchQuery, find some other way around it and then send me a new PR, this one is closed
sir I don't know any other way. Can you please tell me the other way

**Comment by niftyy** [comment]
https://stackoverflow.com/questions/23427384/get-form-data-in-reactjs

**Comment by sggts04** [comment]
Can I work on this?

**Comment by niftyy** [comment]
assigned to @sggts04
