### ISSUE TITLE
Export the MovieRow Component

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#29]
instead of rendering, export the __MovieRow__ component.

**Comment by pradhuman1** [comment]
can i claim this issue

**Comment by niftyy** [comment]
sure

**Comment by JLodha** [comment]
claim

**Comment by pradhuman1** [comment]
Sir can you please explain what to do in this issue

**Comment by niftyy** [comment]
look up on web, how to export react components

**Comment by niftyy** [comment]
this issue is open for claim

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
you already have 2 issues claimed @JLodha .

**Comment by binikingi** [comment]
can i claim?

**Comment by niftyy** [comment]
@binikingi sure
