### ISSUE TITLE
Update the React favicon

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#31]
The current favicon doesn't suit the app, replace it with a new cool icon. Make sure to attach a screenshot with the PR.

**Comment by pradhuman1** [comment]
claim this issue

**Comment by black-cat01** [comment]
can i work on this issue

**Comment by niftyy** [comment]
assigned to @pradhuman1

**Comment by JLodha** [comment]
claim

**Comment by niftyy** [comment]
this issue is open for claim

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
assigned

**Comment by JLodha** [comment]
Sorry but can you assign me the preloader one instead of this.

**Comment by niftyy** [comment]
@JLodha no.
