### ISSUE TITLE
Update the arrow function

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#32]
Currently an arrow function is being used to bind the searchChangeHandler method, replace it with bind method.

**Comment by sggts04** [comment]
claim

**Comment by sggts04** [comment]
Isn't this what I originally did in my scope pr?
this.searchChangeHandler = this.searchChangeHandler.bind(this) in the constructor?

**Comment by niftyy** [comment]
this can be done where the method is called as well.

**Comment by sggts04** [comment]
got it
