### ISSUE TITLE
Update MovieRow Component

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#33]
Currently MovieRow component renders a trivial JSX. It should render a table with 2 columns, one for the movie-poster and another containing 2 row each, the top one for movie-title and bottom for short description of the movie.

**Comment by sggts04** [comment]
claim

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
@JLodha assigned to you

**Comment by JLodha** [comment]
Thanks
