### ISSUE TITLE
Converting Component to react hooks function-based components

### ISSUE THREAD

**Issue by binikingi** [opencodeiiita/MoviesSearch#50]
Change the **_App.js, Footer.js_** and **_MovieRow.js_** to functional component using react hooks

**Comment by sggts04** [comment]
claim

**Comment by sggts04** [comment]
There is no points label?

**Comment by binikingi** [comment]
> There is no points label?

I Don't know if i can add point label. Was planted to wait for responses

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
we are not going to use hooks
