### ISSUE TITLE
Add Movies to state

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#59]
For each search result, create a MovieRow component with relevant data as props and add it to state of the app as an array.

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
assigned @JLodha

**Comment by infern018** [comment]
Claim

**Comment by JLodha** [comment]
Sir can you please explain the question?

**Comment by niftyy** [comment]
you will have to study react state. Task statement is pretty clear

**Comment by JLodha** [comment]
Sir i am unable to complete this task.
Please assign it to someone else
Thanks!

**Comment by niftyy** [comment]
This issue is open for claim.

**Comment by sarthakm21** [comment]
Claim

**Comment by niftyy** [comment]
assigned @sarthakm21

**Comment by blaze-assault** [comment]
Claim it has been inactive

**Comment by sarthakm21** [comment]
Sir give me today's time. I'll get it done...

**Comment by niftyy** [comment]
reassigned to @blaze-assault

**Comment by sggts04** [comment]
Can I work on this?

**Comment by blaze-assault** [comment]
I have one more day left  i will do it by tomorrow.

**Comment by sggts04** [comment]
Can I work on this? Its been inactive

**Comment by niftyy** [comment]
assigned to @sggts04
