### ISSUE TITLE
Change app title to a more suitable color.

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#63]

**Comment by blaze-assault** [comment]
claim

**Comment by sggts04** [comment]
claim

**Comment by niftyy** [comment]
assigned to @blaze-assault . @sggts04 issues are assigned on fcfs basis.

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
@blaze-assault updates ?

**Comment by blaze-assault** [comment]
Sir i message you on slack .but there was no reply .anyways i will make pr by today

**Comment by niftyy** [comment]
cool
