### ISSUE TITLE
Add a black background to the navbar.

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#8]

**Comment by blaze-assault** [comment]
i want to solve this issue

**Comment by niftyy** [comment]
@blaze-assault go for it

**Comment by abhishekbhaware** [comment]
sir is this project assigned to someone

**Comment by niftyy** [comment]
@abhishekbhaware yes

**Comment by JLodha** [comment]
claim

**Comment by harsh-8989** [comment]
can i work

**Comment by niftyy** [comment]
This issue is open for claim now.

**Comment by JLodha** [comment]
Claim

**Comment by niftyy** [comment]
assigned

**Comment by JLodha** [comment]
Sir where is navbar located in the code?

**Comment by niftyy** [comment]
@JLodha there's no html navbar tag, a table is being used in App.js

**Comment by JLodha** [comment]
That means I have to add black colour in respect to that table, right?

**Comment by niftyy** [comment]
yes

**Comment by Devildarkfire** [comment]
claim
