### ISSUE TITLE
Center the search results

### ISSUE THREAD

**Issue by niftyy** [opencodeiiita/MoviesSearch#81]

**Comment by sggts04** [comment]
claim

**Comment by untrulynoxiusmj** [comment]
Claim

**Comment by niftyy** [comment]
assigned to @sggts04

**Comment by sggts04** [comment]
![image](https://user-images.githubusercontent.com/20678047/73560677-67206b00-447d-11ea-97a8-3ad732f1f0b2.png)

Isn't this already centered? What exactly do I need to do?

**Comment by sggts04** [comment]
@niftyy

**Comment by niftyy** [comment]
there should be white columns to the left and right, the results should not stick to the edge of the screen

**Comment by niftyy** [comment]
this issue is open now

**Comment by untrulynoxiusmj** [comment]
claim
